---
title: "CSU Transfers from California Community Colleges"
author: "-Wilmer Tejada"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    runtime: shiny
---


```{r Libraries, include=FALSE}
library(knitr)
library(flexdashboard)
library(tidyverse)
library(lettercase)
library(plotly)
library(shiny)
library(ggthemes)
library(shinyWidgets)
library(rmarkdown)
library(kableExtra)
#library(rsconnect)
```


```{r Load Data, echo = FALSE}
# Source: http://asd.calstate.edu/ccct/2017-2018/SummaryYear.asp
CSU_Transfers = read_csv("data/CSU_Transfers.csv",locale = locale(encoding = 'Latin1'))#because of Canada college.
CSU_Transfers = CSU_Transfers %>% mutate(`College Year` = as.numeric(str_sub(`College Year`, 1,4)))
```


Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
      helpText("Double click on a Campus on the Plot to isolate it.")
      
      selectInput("College", 
                  label = "Select Community College", 
                  choices = unique(CSU_Transfers$`Institution Name`))
      
      prettyCheckboxGroup("Gender", 
                  label = "Select Gender", 
                  choices = unique(CSU_Transfers$Sex),
                  selected  = unique(CSU_Transfers$Sex),
                  icon = icon("check"))
      
      prettyCheckboxGroup("Race", 
                  label = "Select Ethnicity", 
                  choices = unique(CSU_Transfers$`Ethnic Group Desc`),
                  selected = unique(CSU_Transfers$`Ethnic Group Desc`),
                  icon = icon("check"))
      
      sliderInput("Time",
                  label = "Select Timeframe:",
                  min = min(CSU_Transfers$`College Year`),
                  max = max(CSU_Transfers$`College Year`),
                  value = c(min(CSU_Transfers$`College Year`),max(CSU_Transfers$`College Year`)),
                  sep = "")
      
      helpText("Source:\n http://asd.calstate.edu/ccct/2017-2018/SummaryYear.asp")
```

```{r Data Wrangling, echo = FALSE}

dataset1 <- reactive({
CSU = CSU_Transfers %>%
  select(Sex,
         Ethnicity = `Ethnic Group Desc`,
         College = `Institution Name`, 
         `College Year`, 
         TransferCampus = `CSU Campus`, 
         Count = `Number of Transfers`) %>%
  group_by(College,`College Year`,TransferCampus,Sex,Ethnicity) %>% summarise(Count = sum(Count)) %>%
  filter(College == input$College) %>%
  filter(Ethnicity %in% input$Race ) %>%
  filter(Sex %in% input$Gender ) %>%
  filter(`College Year` >= input$Time[1] &
         `College Year` <= input$Time[2]) %>%
   ungroup() %>%
        select(Year = `College Year`,TransferCampus,Count) %>%
        group_by(Year, TransferCampus) %>%
        summarise(Count = sum(Count)) %>%
        arrange(Year) %>%
        ungroup()

})
```
Column {.tabset}
-----------------------------------------------------------------------

### Student Headcounts

```{r}
renderPlotly({
  
 p = dataset1() %>% mutate(Year = as.character(Year)) %>% 
  ggplot(aes(x = Year, y = Count,group = TransferCampus )) +
   geom_point() +
   geom_line(aes(col = TransferCampus)) +
   ggtitle("Transfers to CSU Campuses by Year") +
   theme_fivethirtyeight() +
   scale_y_continuous(breaks = scales::pretty_breaks(n = 10))

 ggplotly(p)
})

```


###  Table 

```{r}

renderUI({
    dataset1() %>%
      spread(key = Year, value = Count) %>%
      column_to_rownames("TransferCampus") %>%
      kable("html")  %>%
      kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
      column_spec(1, bold = T, border_right = T) %>%
      HTML()
    
  }) 
```

```{r}
#deployApp(appName = "CSU_Transfers_from_CCCs")
```

